alter table public.matches
add column if not exists home_possession integer check (home_possession is null or (home_possession >= 0 and home_possession <= 100)),
add column if not exists away_possession integer check (away_possession is null or (away_possession >= 0 and away_possession <= 100)),
add column if not exists home_offsides integer check (home_offsides is null or home_offsides >= 0),
add column if not exists away_offsides integer check (away_offsides is null or away_offsides >= 0),
add column if not exists home_corners integer check (home_corners is null or home_corners >= 0),
add column if not exists away_corners integer check (away_corners is null or away_corners >= 0),
add column if not exists home_total_shots integer check (home_total_shots is null or home_total_shots >= 0),
add column if not exists away_total_shots integer check (away_total_shots is null or away_total_shots >= 0),
add column if not exists home_shots integer check (home_shots is null or home_shots >= 0),
add column if not exists away_shots integer check (away_shots is null or away_shots >= 0),
add column if not exists home_shots_on_target integer check (home_shots_on_target is null or home_shots_on_target >= 0),
add column if not exists away_shots_on_target integer check (away_shots_on_target is null or away_shots_on_target >= 0),
add column if not exists home_blocked_shots integer check (home_blocked_shots is null or home_blocked_shots >= 0),
add column if not exists away_blocked_shots integer check (away_blocked_shots is null or away_blocked_shots >= 0),
add column if not exists home_goalkeeper_saves integer check (home_goalkeeper_saves is null or home_goalkeeper_saves >= 0),
add column if not exists away_goalkeeper_saves integer check (away_goalkeeper_saves is null or away_goalkeeper_saves >= 0),
add column if not exists home_tackles integer check (home_tackles is null or home_tackles >= 0),
add column if not exists away_tackles integer check (away_tackles is null or away_tackles >= 0),
add column if not exists home_passes integer check (home_passes is null or home_passes >= 0),
add column if not exists away_passes integer check (away_passes is null or away_passes >= 0),
add column if not exists home_completed_passes integer check (home_completed_passes is null or home_completed_passes >= 0),
add column if not exists away_completed_passes integer check (away_completed_passes is null or away_completed_passes >= 0);
